### ISSUE TITLE
Azure Redis MSI not working for Redis instances in non Microsoft Tenant

### ISSUE THREAD

**Issue by Tommykewl** [Azure/Microsoft.Azure.StackExchangeRedis#14]
Redis MSI is not working for non Microsoft Tenant.While following the [documentation](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication) we tried to implement it. Its working for Azure Cache in Microsoft tenant but not working in PME ( custom internal tenant). On digging in the code provided in Microsoft.Azure.StackExchangeRedis, we found out that the audience is hard coded [here](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/blob/2ca6c787c40037094fa0bd05cb96962e9fe46cbe/src/CacheIdentityClient.cs#LL26C8-L26C8)

I have used the sample provided by the SDK provided by Azure. While running the Sample with our setup values, we are getting the following exception

```
Options for connecting to an Azure Cache for Redis resource: 
            1. Authenticate using an access key
            2. Authenticate using a system-assigned managed identity
            3. Authenticate using a user-assigned managed identity
            4. Authenticate using service principal
            5. Exit
 
Enter a number: 3
Redis cache host name: pst-int-westus.geo.redis.cache.windows.net
Managed identity Client ID or resource ID: b5aac26a-4dbf-44c2-8118-62490d80faed
Managed identity Principal (object) ID ('Username' from the 'Data Access Configuration' blade on the Azure Cache for Redis resource): b5aac26a-4dbf-44c2-8118-62490d80faed
Connecting with a user-assigned managed identity...
Failed to connect: System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (169.254.169.254:80)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.StackExchangeRedis.AzureCacheOptionsProviderWithToken.AcquireTokenAsync(Boolean forceRefresh, Boolean throwOnFailure) in C:\__w\1\s\src\AzureCacheOptionsProviderWithToken.cs:line 200
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureAsync(ConfigurationOptions configurationOptions, AzureCacheOptions azureCacheOptions) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 93
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureWithUserAssignedManagedIdentityAsync(ConfigurationOptions configurationOptions, String clientId, String principalId) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 49
   at MyWinTrust.Program.Main(String[] args) in C:\Users\tabiswas\source\repos\RPE.Partner.Service.BizOps\PrOSE\MyWinTrust\Program.cs:line 61
 
Connection log from StackExchange.Redis:
 
 
C:\Users\tabiswas\source\repos\RPE.Partner.Service.BizOps\PrOSE\MyWinTrust\bin\Release\net6.0\MyWinTrust.exe (process 16160) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

Its not a network issue. If I try to run the same sample console application with option with connectionString I'm able to get connected from my local machine on running the console application. For option 3 ( user assigned MSI, its failing )

Logs -
```
Options for connecting to an Azure Cache for Redis resource: 
            1. Authenticate using an access key
            2. Authenticate using a system-assigned managed identity
            3. Authenticate using a user-assigned managed identity
            4. Authenticate using service principal
            5. Exit
Enter a number: 1
Redis cache connection string: pst-int-westus.geo.redis.cache.windows.net:6380,password=<redacted_password>=,ssl=True,abortConnect=False
Connecting with an access key...
Connected successfully!
Connection log from StackExchange.Redis:
09:48:12.4642: Connecting (sync) on .NET 6.0.18 (StackExchange.Redis: v2.6.111.64013)
09:48:12.6260: pst-int-westus.geo.redis.cache.windows.net:6380,password=*****,ssl=True,abortConnect=False
09:48:12.6409: pst-int-westus.geo.redis.cache.windows.net:6380/Interactive: Connecting...
09:48:12.6777: pst-int-westus.geo.redis.cache.windows.net:6380: BeginConnectAsync
09:48:12.7361: 1 unique nodes specified (with tiebreaker)
09:48:12.7378: pst-int-westus.geo.redis.cache.windows.net:6380: OnConnectedAsync init (State=Connecting)
09:48:12.7389: Allowing 1 endpoint(s) 00:00:05 to respond...
09:48:12.7448: Awaiting 1 available task completion(s) for 5000ms, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=0,Free=32767,Min=8,Max=32767), POOL: (Threads=0,QueuedItems=0,CompletedItems=0)
09:48:13.2023: Configuring TLS
09:48:13.7418: TLS connection established successfully using protocol: Tls12
09:48:13.7439: pst-int-westus.geo.redis.cache.windows.net:6380/Interactive: Connected
09:48:13.7576: pst-int-westus.geo.redis.cache.windows.net:6380: Server handshake
09:48:13.7577: pst-int-westus.geo.redis.cache.windows.net:6380: Authenticating (password)
09:48:13.8348: pst-int-westus.geo.redis.cache.windows.net:6380: Setting client name: MININT-KODICEF(SE.Redis-v2.6.111.64013)
09:48:13.8363: pst-int-westus.geo.redis.cache.windows.net:6380: Setting client lib/ver
09:48:13.8453: pst-int-westus.geo.redis.cache.windows.net:6380: Auto-configuring...
09:48:13.8469: pst-int-westus.geo.redis.cache.windows.net:6380: Requesting tie-break (Key="__Booksleeve_TieBreak")...
09:48:13.8484: pst-int-westus.geo.redis.cache.windows.net:6380/Interactive: Writing: GET __Booksleeve_TieBreak
09:48:13.8490: pst-int-westus.geo.redis.cache.windows.net:6380: Sending critical tracer (handshake): ECHO
09:48:13.8490: pst-int-westus.geo.redis.cache.windows.net:6380/Interactive: Writing: ECHO
09:48:13.8491: pst-int-westus.geo.redis.cache.windows.net:6380: Flushing outbound buffer
09:48:13.8491: pst-int-westus.geo.redis.cache.windows.net:6380: OnEstablishingAsync complete
09:48:13.8491: pst-int-westus.geo.redis.cache.windows.net:6380: Starting read
09:48:14.0836: pst-int-westus.geo.redis.cache.windows.net:6380: Auto-configured (INFO) role: primary
09:48:14.0842: pst-int-westus.geo.redis.cache.windows.net:6380: Auto-configured (INFO) version: 6.0.14
09:48:14.0842: pst-int-westus.geo.redis.cache.windows.net:6380: Auto-configured (INFO) server-type: standalone
09:48:14.0851: Response from pst-int-westus.geo.redis.cache.windows.net:6380/Interactive / GET __Booksleeve_TieBreak: (null)
09:48:14.0856: Response from pst-int-westus.geo.redis.cache.windows.net:6380/Interactive / ECHO: BulkString: 16 bytes
09:48:14.0868: pst-int-westus.geo.redis.cache.windows.net:6380: OnConnectedAsync completed (From command: ECHO)
09:48:14.0879: All 1 available tasks completed cleanly, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767), POOL: (Threads=7,QueuedItems=0,CompletedItems=18)
09:48:14.0885: Endpoint summary:
09:48:14.0885:   pst-int-westus.geo.redis.cache.windows.net:6380: Endpoint is (Interactive: ConnectedEstablished, Subscription: ConnectedEstablished)
09:48:14.0885: Task summary:
09:48:14.0885:   pst-int-westus.geo.redis.cache.windows.net:6380: Returned with success as Standalone primary (Source: From command: ECHO)
09:48:14.0921: Election summary:
09:48:14.0921:   Election: pst-int-westus.geo.redis.cache.windows.net:6380 had no tiebreaker set
09:48:14.0921:   Election: Single primary detected: pst-int-westus.geo.redis.cache.windows.net:6380
09:48:14.0921: pst-int-westus.geo.redis.cache.windows.net:6380: Clearing as RedundantPrimary
09:48:14.0928: Endpoint Summary:
09:48:14.0942:   pst-int-westus.geo.redis.cache.windows.net:6380: Standalone v6.0.14, primary; keep-alive: 00:01:00; int: ConnectedEstablished; sub: ConnectedEstablished, 1 active
09:48:14.0956:   pst-int-westus.geo.redis.cache.windows.net:6380: int ops=13, qu=0, qs=1, qc=0, wr=0, socks=1; sub ops=6, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1
09:48:14.1017:   pst-int-westus.geo.redis.cache.windows.net:6380: Circular op-count snapshot; int: 0+13=13 (1.30 ops/s; spans 10s); sub: 0+6=6 (0.60 ops/s; spans 10s)
09:48:14.1019: Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
09:48:14.1021: Starting heartbeat...
09:48:14.3402: Total connect time: 1,881 ms
```
```[tasklist]
### Tasks
```

**Comment by philon-msft** [comment]
Closing this to clean up. Please reactivate if necessary
