### ISSUE TITLE
Is there any plan to support new version of Microsoft.Identity.Client?

### ISSUE THREAD

**Issue by wakinpang** [Azure/Microsoft.Azure.StackExchangeRedis#15]
since my project used 4.55 version of Microsoft.Identity.Client, there is some dependency problem about can't resolve right method. And as I checked, the method in it  ManagedIdentityApplicationBuilder.Create has changed (they changed the method's parameter, but do not support the old one), does not support use a string parameter directly.

It's OK for me, I can downgrade my package reference to 4.53 resolve it, but is there any plan for it?

**Comment by rudiv** [comment]
This is a silly blocker, possibly on the part of Microsoft.Identity.Web for changing the API.

For anyone else that encounters this issue and if you're using `Microsoft.Identity.Web`, to save you some time you need to downgrade this package to version `2.10.0` to get the dependency down to `4.53`.

**Comment by onionhammer** [comment]
I assume this is why I'm getting 

> Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.Identity.Client.ManagedIdentityApplicationBuilder Microsoft.Identity.Client.ManagedIdentityApplicationBuilder.Create(System.String)'.
   at Microsoft.Azure.StackExchangeRedis.CacheIdentityClient.CreateForUserAssignedManagedIdentity(String clientId)
   at Microsoft.Azure.StackExchangeRedis.AzureCacheOptionsProviderWithToken.GetIdentityClient(AzureCacheOptions azureCacheOptions) in C:\__w\1\s\src\AzureCacheOptionsProviderWithToken.cs:line 84
   at Microsoft.Azure.StackExchangeRedis.AzureCacheOptionsProviderWithToken..ctor(AzureCacheOptions azureCacheOptions) in C:\__w\1\s\src\AzureCacheOptionsProviderWithToken.cs:line 43
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureAsync(ConfigurationOptions configurationOptions, AzureCacheOptions azureCacheOptions) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 91
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureWithUserAssignedManagedIdentityAsync(ConfigurationOptions configurationOptions, String clientId, String principalId) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 49

**Comment by lsannicolas** [comment]
Hello, we'll be adding support in a future version

**Comment by onionhammer** [comment]
@lsannicolas that was fast - support is already complete?

**Comment by lsannicolas** [comment]
We haven't created the PR yet. I'll reopen the issue and link the pr once that is posted

**Comment by harika-g** [comment]
When will the support for 4.55 version of Microsoft.Identity.Client be added?

**Comment by lsannicolas** [comment]
We’re hoping to add it in the next version release, but there’s no date set for that just yet. I can update here once we get a better idea of a timeline

**Comment by philon-msft** [comment]
The new release v2.0.0 uses the latest Microsoft.Client.Identity package. Please give it a try and let us know if you still see any issues.
