### ISSUE TITLE
Authentication fails for System Assigned Managed Identity

### ISSUE THREAD

**Issue by sven5** [Azure/Microsoft.Azure.StackExchangeRedis#23]
I'm getting the following Error in ASP.NET Core 6.0 app

```
CoreCLR Version: 6.0.2023.32017
.NET Version: 6.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: MSAL.NetCore.4.53.0.0.MsalServiceException: 
	ErrorCode: managed_identity_request_failed
Microsoft.Identity.Client.MsalServiceException: [Managed Identity] Error Message: Unable to load the proper Managed Identity. Managed Identity Correlation ID: 2f8bd974-4c27-42c3-bf79-e21920742069 Use this Correlation ID for further investigation.
   at Microsoft.Azure.StackExchangeRedis.AzureCacheOptionsProviderWithToken.AcquireTokenAsync(Boolean forceRefresh, Boolean throwOnFailure) in C:\__w\1\s\src\AzureCacheOptionsProviderWithToken.cs:line 200
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureAsync(ConfigurationOptions configurationOptions, AzureCacheOptions azureCacheOptions) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 93
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureWithSystemAssignedManagedIdentityAsync(ConfigurationOptions configurationOptions, String principalId) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 32
   at Vonovia.Web.StartupEx`2.&lt;&gt;c__DisplayClass87_2.&lt;&lt;ConfigureSessionServices&gt;b__2&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.&lt;&gt;c.&lt;.cctor&gt;b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState&amp; state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by sven5** [comment]
The same error is happening running the Sample.cs on Azure App Service Console.

**Comment by philon-msft** [comment]
Are you using the System Assigned Identity of the Azure VM where the app is running?

**Comment by sven5** [comment]
@philon-msft 
No, I'm using the System Assigned Identity of the Redis Cache.

**Comment by philon-msft** [comment]
Closing to clean up. Let us know if you see any other issues
