### ISSUE TITLE
HttpRequestException: A socket operation was attempted to an unreachable network. (169.254.169.254:80)

### ISSUE THREAD

**Issue by shivatk** [Azure/Microsoft.Azure.StackExchangeRedis#5]
Should the sample app be run only in an Azure managed VM/container?

Running the sample outside Azure fails with

```
Failed to connect: System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (169.254.169.254:80)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.StackExchangeRedis.AzureCacheOptionsProviderWithToken.AcquireTokenAsync(Boolean forceRefresh, Boolean throwOnFailure) in C:\__w\1\s\src\AzureCacheOptionsProviderWithToken.cs:line 200
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureAsync(ConfigurationOptions configurationOptions, AzureCacheOptions azureCacheOptions) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 93
   at StackExchange.Redis.AzureCacheForRedis.ConfigureForAzureWithUserAssignedManagedIdentityAsync(ConfigurationOptions configurationOptions, String clientId, String principalId) in C:\__w\1\s\src\AzureCacheForRedis.cs:line 49
   at Program.<Main>$(String[] args) in C:\Users\shivath\Desktop\Scripts\Redis_AAD\sample\Sample.cs:line 5
```

 169.254.169.254 is a loop back IP for the Azure resource's metadata endpoint, yes? How can I tell the sample app to go the actual OAuth endpoint to fetch a token?

**Comment by philon-msft** [comment]
Yes, this extension currently only works when run on an Azure compute resource that supports Azure.Identity. See #2 for a suggestion to add support for running on other clients. To bypass Azure.Identity, your code could use the Azure.Core GetTokenAsync method mentioned there, rather than the extension

**Comment by shivatk** [comment]
Got it. Thanks Phil.
