### ISSUE TITLE
Unauthorize error After installed Microsoft.Azure.StackExchangeRedis package

### ISSUE THREAD

**Issue by raghu-gade** [Azure/Microsoft.Azure.StackExchangeRedis#68]
I'm using Microsoft.AspNetCore.Authorization for Authorization and implemented working fine and authorize with valid token initially, after implementing Redis cache package Microsoft.Azure.StackExchangeRedis it's showing unauthorize error with valid token. For Cross verify i was removed this package and try it's Authorize perfectly. Here is my authorization code
```
public void ConfigureServices(IServiceCollection services)
{
  services.AddAuthentication(ServerAuthenticationDefaults.AuthenticationScheme)
             .AddIdentityServerAuthentication(options =>
             {
                 options.Authority = ServerConfig.Authority;
                 options.ApiName = ServerConfig.APIApplicationId;
                 options.RequireHttpsMetadata = false; 
                 options.JwtBackChannelHandler = new HttpClientHandler
                 {
                     ServerCertificateCustomValidationCallback = delegate { return true; }
                 };
             });
}
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseAuthentication();
    app.UseAuthorization();
}
```
```
using Microsoft.AspNetCore.Authorization;
 [Authorize]
 [Route("api/config")]
 public class ConfigurationController : ControllerBase
 {
 }
```
Here is my Redis cache code
```
using Azure.Identity;
using StackExchange.Redis;
private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
  {
          var credential = new DefaultAzureCredential();
          string cacheConnectionEndpoint = ConfigurationUtil.GetSetting("RedisCacheConnectionString"); 
          var configurationOptions = ConfigurationOptions.Parse($"{cacheConnectionEndpoint}:6380").ConfigureForAzureWithTokenCredentialAsync(credential);
          configurationOptions.Result.AbortOnConnectFail = false;
          configurationOptions.Result.SyncTimeout = 60000;
          return ConnectionMultiplexer.Connect(configurationOptions.Result);
       });

  public static ConnectionMultiplexer Connection
  {
      get
      {
          try
          {
              return lazyConnection.Value;
          }
          catch
          {
              return null;
          }
      }
  }
```
Is there any alternate Package for Microsoft.Azure.StackExchangeRedis

**Comment by philon-msft** [comment]
What version of Microsoft.Azure.StackExchangeRedis did you integrate? Versions before 3.2.0 referenced older versions of some dependency packages that might be shared with Microsoft.AspNetCore.Authorization and causing problems.

**Comment by raghu-gade** [comment]
I'm using Microsoft.Azure.StackExchangeRedis 3.2.0 version and my project version is **net8.0** .

**Comment by philon-msft** [comment]
If you're on 3.2.0 and .NET 8, it's unlikely that dependencies are causing the problems. Is the "unauthorized" error coming from Redis or other code. I recommend confirming that DefaultAzureCredential() is picking up an identity that has been assigned to a data access policy per https://learn.microsoft.com/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication

**Comment by MagnusJohansson** [comment]
I have the same problem. 
Just simply adding the Nuget package "Microsoft.Azure.StackExchangeRedis" (without any code using any Redis stuff) , just simply breaks my ASPNET Core 8.0 Web Authentication.
The only error I see in the log is:
```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
      Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
         at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignature(JsonWebToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
         at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignatureAndIssuerSecurityKey(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
         at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateJWSAsync(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
dbug: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[9]
      AuthenticationScheme: Bearer was not authenticated.
```

**Comment by philon-msft** [comment]
Apparently this is caused by version mismatches between different Microsoft.IdentityModel.* packages. Upgrading all Microsoft.IdentityModel.* package references to 8.1.2 to match Microsoft.Azure.StackExchangeRedis's reference to Microsoft.IdentityModel.JsonWebTokens should help. 

Details: https://stackoverflow.com/a/78442187/11838861
